name: actions

on: push

jobs:
  my_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: project setup
        run: make setup
      - name: test execution
        run: make test
      - name: linter check
        run: make lint
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.d8d81acc-8350-4128-b63f-2f50421a2f3f snyk test }}
